# Project information
site_name: Testing Mkdocs
site_description: Repo for testing Mkdocs
site_author: Jim Andreas
site_url: https://jimandreas.github.io/TestRepoMkdocsPage/

# Repository
repo_name: jimandreas/TestRepoMkdocsPage
repo_url: https://github.com/jimandreas/TestRepoMkdocsPage
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 Jim Andreas

# Configuration
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/sandbox_transparent.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
#  language: en
#  palette:
#    - scheme: default
#      primary: indigo
#      accent: indigo
#  font:
#    text: Roboto
#    code: Roboto Mono

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jimandreas
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jimandreasdev
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jimandreas

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true

